# Generated by Django 6.0.3 on 2026-03-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
